# Generated by Django 5.0.2 on 2024-03-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.DurationField(blank=True, null=True, verbose_name='время на выполнение'),
        ),
    ]
